python -u proposal.py  \
    --do_train True\
    --do_eval False\
    --do_predict True\
    --path ../data/2010i2b2-UMLS/ \
    --pred True\
    --result ./result/  \
    --name proposal-bce\
    --tokenizer allenai/scibert_scivocab_uncased \
    --text_model /media/sda1/RelationExtraction/REMOD-General/pretrained-models-i2b2/text/scibert-epoch-28/ \
    --graph_model /media/sda1/RelationExtraction/REMOD-General/pretrained-models-i2b2/graph/GraphEncoderScore-epoch-490.pth \
    --feat_dim 100 \
    --layer_num 1 \
    --maxLength 512  \
    --trainBatchSize 8 \
    --testBatchSize 16  \
    --weightDecay 5e-7  \
    --epoch 30  \
    --lr 3e-5  \
    --accumulate_step 4  \
    --nworkers 4 \
    --pinMemory True\
    --distill True\
    --cuda 1
